################################################################
# ATENTION:
#
# Replace all occurences of sandbox with your project's name
#
# Thank's to @hernandev
################################################################

version: '3.4'
services:
  app:
    image: ambientum/php:7.2-nginx
    container_name: sandbox-app
    ports:
      - 80:8080
    volumes:
      - .:/var/www/app
    depends_on:
      - pgsql
      - mariadb
      - redis
    links:
      - pgsql
      - mariadb
      - redis
    networks:
      - laravel

  pgsql:
    image: postgres:10.2-alpine
    container_name: sandbox-pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - laravel

  mariadb:
    image: mariadb:10.3
    container_name: sandbox-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sandbox
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: sandbox
    volumes:
      - mariadb:/var/lib/mariadb
    networks:
      - laravel

  redis:
    image: redis:4.0.8-alpine
    container_name: sandbox-redis
    command: --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
     - laravel

  selenium:
    image: selenium/standalone-chrome
    container_name: sandbox-selenium
    networks:
     - laravel

  npm:
    image: ambientum/node:9
    container_name: sandbox-npm
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080

networks:
  laravel:
    driver: bridge
volumes:
  pgsql:
    driver: local
  mariadb:
    driver: local
  redis:
    driver: local
