################################################################
# ATENTION:
#
# Replace all occurences of sandbox with your project's name
#
# Thank's to @hernandev
################################################################

# v3 syntax
version: '3'

# Named volumes
volumes:
  # Postgres Data
  sandbox-postgres-data:
    driver: local

  # Redis Data
  sandbox-redis-data:
    driver: local

services:
  # Postgres (10.2)
  postgres:
    image: postgres:10.2-alpine
    container_name: sandbox-postgres
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_DB=sandbox
      - POSTGRES_USER=sandbox

  # Redis
  cache:
    image: redis:4.0.8-alpine
    container_name: sandbox-redis
    command: --appendonly yes
    volumes:
      - sandbox-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: sandbox-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - cache

  # Laravel Horizon
  horizon:
    image: ambientum/php:7.2
    container_name: sandbox-horizon
    command: php artisan horizon
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
